#!/bin/sh
set -e
# Automatically added by dh_icons/12.6.1ubuntu2
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/workspaces-branding
fi
# End automatically added section
